variables:
  OPENSHIFT_CLIENT_TOOLS_DOWNLOAD_URL: https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
  # use https://download.svcat.sh/cli/latest/linux/amd64/svcat for latest version.
  # using v0.1.30 for now as v0.1.37 fails to sync broker in 3.10
  SERVICE_CATALOG_CLI_DOWNLOAD_URL: https://download.svcat.sh/cli/v0.1.30/linux/amd64/svcat
  #
  KUBECTL_DOWNLOAD_BASE: https://storage.googleapis.com/kubernetes-release/release
  KUBECTL_DOWNLOAD_TAIL: bin/linux/amd64/kubectl
  KUBECTL_RELEASE: https://storage.googleapis.com/kubernetes-release/release/stable.txt
  #

build_kaniko_command:
    stage: build
    image:
        # We recommend using the CERN version of the Kaniko image: gitlab-registry.cern.ch/ci-tools/docker-image-builder
        name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
        entrypoint: [""]
    script:
        # Prepare Kaniko configuration file
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        # Build and push the image from the Dockerfile at the root of the project.
        # To push to a specific docker tag, amend the --destination parameter, e.g. --destination $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
        # See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference for available variables
        - /kaniko/executor --build-arg OPENSHIFT_CLIENT_TOOLS_DOWNLOAD_URL=$OPENSHIFT_CLIENT_TOOLS_DOWNLOAD_URL --build-arg SERVICE_CATALOG_CLI_DOWNLOAD_URL=$SERVICE_CATALOG_CLI_DOWNLOAD_URL --build-arg KUBECTL_DOWNLOAD_BASE=$KUBECTL_DOWNLOAD_BASE --build-arg KUBECTL_DOWNLOAD_TAIL=$KUBECTL_DOWNLOAD_TAIL --build-arg KUBECTL_RELEASE=$KUBECTL_RELEASE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE

